#!/bin/bash

set -e


# Check to see if we should even start
snap_mode=$(cat $SNAP_COMMON/snap_mode)
if ! [[ $snap_mode == "slurmctld" || $snap_mode = "all" ]]; then
        exit 0
fi


export SLURM_CONF=$SNAP_COMMON/etc/slurm/slurm.conf
export SLURMCTLD_LOG=$SNAP_COMMON/var/log/slurm/slurmctld.log


# Start slurmctld only if we have a config file
if ! [[ -f $SLURM_CONF ]]; then
    printf "No slurm conf, cannot start process.";
    exit -1
fi

printf "Starting SLURMCTLD";
exec "$SNAP/usr/sbin/slurmctld" \
    "-f" "$SLURM_CONF" \
    "-L" "$SLURMCTLD_LOG" \
    "-D" "$@"
