#!/bin/bash


set -e

# Only proceed if the snap.mode is set to one of
# "slurmdbd", "all", or "slurmdbd+manual"
snap_mode=$(cat $SNAP_COMMON/snap_mode)
if ! [[ $snap_mode == "slurmdbd" ]]; then
        exit 1
fi


# Start slurmdbd only if we have a config file
if ! [[ -f $SLURM_CONF ]]; then
    printf "No slurm conf, cannot start process.";
    exit -1
fi

printf "Starting SLURMDBD";
exec "$SNAP/bins/slurmdbd" "-D" "$@"
