#!/bin/bash


set -e

# Check to see if we should even start
snap_mode=$(cat $SNAP_COMMON/snap_mode)
if ! [[ $snap_mode == "slurmrestd" ]]; then
        exit 0
fi


export SLURM_CONF=$SNAP_COMMON/etc/slurm/slurm.conf


# Start slurmrestd only if we have a config file
if ! [[ -f $SLURM_CONF ]]; then
    printf "No slurm conf, cannot start process.";
    exit -1
fi


# Export empty SLURM_JWT to activate the jwt auth plugin in slurmrestd.
# https://slurm.schedmd.com/rest.html
export SLURM_JWT=


printf "Starting SLURMRESTD";
exec "$SNAP/usr/sbin/slurmrestd" \
    "-f" "$SLURM_CONF" `hostname -s`:6820 "$@" 
