#!/bin/bash


set -e

# Check to see if we should even start
snap_mode=$(cat $SNAP_COMMON/snap_mode)
if ! [[ $snap_mode == "slurmd" || $snap_mode = "all" ]]; then
        exit 0
fi


export SLURM_CONF="$SNAP_COMMON/etc/slurm/slurm.conf"
export SLURMD_LOG="$SNAP_COMMON/var/log/slurm/slurmd.log"
export SLURMCTLD_HOSTNAME="$SNAP_COMMON/slurmctld_hostname"

# Start slurmd only if we have a config file
if [ ! -f $SLURM_CONF ] && [ ! -f $SLURMCTLD_HOSTNAME ]; then
    printf "No slurm conf, cannot start process.";
    exit -1
fi

printf "Starting SLURMD";

if [ ! -f $SLURMCTLD_HOSTNAME ]; then
    exec "$SNAP/usr/sbin/slurmd" \
         "-f" "$SLURM_CONF" \
         "-d" "$SNAP/usr/sbin/slurmstepd" \
         "-L" "$SLURMD_LOG" \
         "-D" "$@"
else
    slurmctld=$(cat $SLURMCTLD_HOSTNAME)
    exec "$SNAP/usr/sbin/slurmd" \
	 "--conf-server" $slurmctld \
         "-f" "$SLURM_CONF" \
         "-d" "$SNAP/usr/sbin/slurmstepd" \
         "-L" "$SLURMD_LOG" \
         "-D" "$@"
fi
